# Generated by Django 5.0.1 on 2024-01-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=50, verbose_name='Página')),
                ('image', models.ImageField(upload_to='shop', verbose_name='Imagen')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre videojuego')),
                ('precio', models.CharField(max_length=50, verbose_name='Precio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'videojuego',
                'verbose_name_plural': 'videojuegos',
                'ordering': ['-created'],
            },
        ),
    ]
